/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pecl.pa;

import java.rmi.Naming;
import java.rmi.RemoteException;
import javax.swing.SwingUtilities;

/**
 *
 * @author julia_ntxs1ki
 */
public class InterfazRemota extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InterfazRemota.class.getName());
    private InterfazMundo mundoRemoto;

    /**
     * Creates new form InterfazRemota
     */
    public InterfazRemota() {
        initComponents();

        try {
            mundoRemoto = (InterfazMundo) Naming.lookup("rmi://localhost:1099/MundoStranger");

            Thread hiloActualizar = new Thread(() -> {
                while (true) {
                    try {
                        actualizarRemoto();
                        Thread.sleep(1000);
                    } catch (Exception e) {
                        System.err.println("Error actualizando interfaz remota: " + e.getMessage());
                    }
                }
            });

            hiloActualizar.setDaemon(true);
            hiloActualizar.start();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void actualizarRemoto() {
    try {
        int hawkins = mundoRemoto.getHawkinsRemoto();

        int nBosque = mundoRemoto.getNiñosBosqueRemoto();
        int nLab = mundoRemoto.getNiñosLaboratorioRemoto();
        int nCentro = mundoRemoto.getNiñosCentroComercialRemoto();
        int nAlc = mundoRemoto.getNiñosAlcantarilladoRemoto();
        int nColmena = mundoRemoto.getNiñosColmenaRemoto();

        int dBosque = mundoRemoto.getDemogorgonsBosqueRemoto();
        int dLab = mundoRemoto.getDemogorgonsLaboratorioRemoto();
        int dCentro = mundoRemoto.getDemogorgonsCentroComercialRemoto();
        int dAlc = mundoRemoto.getDemogorgonsAlcantarilladoRemoto();
        
        int portal1 = mundoRemoto.getPortal1Remoto();
        int portal2 = mundoRemoto.getPortal2Remoto();
        int portal3 = mundoRemoto.getPortal3Remoto();
        int portal4 = mundoRemoto.getPortal4Remoto();

        String evento = mundoRemoto.getEventoActualRemoto();
        int tiempoEvento = mundoRemoto.getTiempoEventoRemoto();

        SwingUtilities.invokeLater(() -> {
            niñosHawkingstxt.setText(String.valueOf(hawkins));

            niñosBosquetxt.setText(String.valueOf(nBosque));
            niñosLaboratoriotxt.setText(String.valueOf(nLab));
            niñosCentroComercialtxt.setText(String.valueOf(nCentro));
            niñosAlcantarilladotxt.setText(String.valueOf(nAlc));
            niñosColmenatxt.setText(String.valueOf(nColmena));

            demogorgonsBosquetxt.setText(String.valueOf(dBosque));
            demogorgonsLaboratoriotxt.setText(String.valueOf(dLab));
            demogorgonsCentroComercialtxt.setText(String.valueOf(dCentro));
            demogorgonsAlcantarilladotxt.setText(String.valueOf(dAlc));
            
            portal1txt.setText(String.valueOf(portal1));
            portal2txt.setText(String.valueOf(portal2));
            portal3txt.setText(String.valueOf(portal3));
            portal4txt.setText(String.valueOf(portal4));
            
            try {
                rankingtxt.setText(mundoRemoto.getRankingDemogorgonsRemoto());
            } catch (RemoteException ex) {
                System.getLogger(InterfazRemota.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
            
            eventotxt.setText(evento);
            tiempoEventotxt.setText(tiempoEvento + " s");
        });

    } catch (Exception e) {
        System.err.println("Error RMI: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        niñosHawkingstxt = new javax.swing.JTextField();
        portal1txt = new javax.swing.JTextField();
        portal2txt = new javax.swing.JTextField();
        portal3txt = new javax.swing.JTextField();
        portal4txt = new javax.swing.JTextField();
        niñosBosquetxt = new javax.swing.JTextField();
        niñosLaboratoriotxt = new javax.swing.JTextField();
        niñosCentroComercialtxt = new javax.swing.JTextField();
        niñosAlcantarilladotxt = new javax.swing.JTextField();
        niñosColmenatxt = new javax.swing.JTextField();
        demogorgonsBosquetxt = new javax.swing.JTextField();
        demogorgonsLaboratoriotxt = new javax.swing.JTextField();
        demogorgonsCentroComercialtxt = new javax.swing.JTextField();
        demogorgonsAlcantarilladotxt = new javax.swing.JTextField();
        eventotxt = new javax.swing.JTextField();
        tiempoEventotxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        rankingtxt = new javax.swing.JTextArea();
        btnReanudar = new javax.swing.JButton();
        btnPausa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1150, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        niñosHawkingstxt.setEditable(false);
        getContentPane().add(niñosHawkingstxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 50, 40));

        portal1txt.setEditable(false);
        getContentPane().add(portal1txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        portal2txt.setEditable(false);
        getContentPane().add(portal2txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        portal3txt.setEditable(false);
        getContentPane().add(portal3txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        portal4txt.setEditable(false);
        getContentPane().add(portal4txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        niñosBosquetxt.setEditable(false);
        getContentPane().add(niñosBosquetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, -1));

        niñosLaboratoriotxt.setEditable(false);
        getContentPane().add(niñosLaboratoriotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, -1));

        niñosCentroComercialtxt.setEditable(false);
        getContentPane().add(niñosCentroComercialtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, -1, -1));

        niñosAlcantarilladotxt.setEditable(false);
        getContentPane().add(niñosAlcantarilladotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, -1, -1));

        niñosColmenatxt.setEditable(false);
        getContentPane().add(niñosColmenatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, -1, -1));

        demogorgonsBosquetxt.setEditable(false);
        getContentPane().add(demogorgonsBosquetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, -1, -1));

        demogorgonsLaboratoriotxt.setEditable(false);
        getContentPane().add(demogorgonsLaboratoriotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, -1, -1));

        demogorgonsCentroComercialtxt.setEditable(false);
        getContentPane().add(demogorgonsCentroComercialtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, -1, -1));

        demogorgonsAlcantarilladotxt.setEditable(false);
        getContentPane().add(demogorgonsAlcantarilladotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, -1, -1));

        eventotxt.setEditable(false);
        getContentPane().add(eventotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, 240, 50));

        tiempoEventotxt.setEditable(false);
        getContentPane().add(tiempoEventotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, -1, 50));

        rankingtxt.setEditable(false);
        rankingtxt.setColumns(20);
        rankingtxt.setRows(5);
        jScrollPane1.setViewportView(rankingtxt);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, 120, 110));

        btnReanudar.setText("REANUDAR");
        btnReanudar.addActionListener(this::btnReanudarActionPerformed);
        getContentPane().add(btnReanudar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, -1, -1));

        btnPausa.setText("PAUSAR");
        btnPausa.addActionListener(this::btnPausaActionPerformed);
        getContentPane().add(btnPausa, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReanudarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReanudarActionPerformed
        // TODO add your handling code here:
        btnPausa.setEnabled(true);
        btnReanudar.setEnabled(false);
        try {
            mundoRemoto.reanudarRemoto();
        } catch (RemoteException ex) {
            System.getLogger(InterfazRemota.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_btnReanudarActionPerformed

    private void btnPausaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPausaActionPerformed
        // TODO add your handling code here:
        btnPausa.setEnabled(false);    // Desactivar pausa si ya está pausado
        btnReanudar.setEnabled(true);
        try {
            mundoRemoto.pausarRemoto();
        } catch (RemoteException ex) {
            System.getLogger(InterfazRemota.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_btnPausaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InterfazRemota().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPausa;
    private javax.swing.JButton btnReanudar;
    private javax.swing.JTextField demogorgonsAlcantarilladotxt;
    private javax.swing.JTextField demogorgonsBosquetxt;
    private javax.swing.JTextField demogorgonsCentroComercialtxt;
    private javax.swing.JTextField demogorgonsLaboratoriotxt;
    private javax.swing.JTextField eventotxt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField niñosAlcantarilladotxt;
    private javax.swing.JTextField niñosBosquetxt;
    private javax.swing.JTextField niñosCentroComercialtxt;
    private javax.swing.JTextField niñosColmenatxt;
    private javax.swing.JTextField niñosHawkingstxt;
    private javax.swing.JTextField niñosLaboratoriotxt;
    private javax.swing.JTextField portal1txt;
    private javax.swing.JTextField portal2txt;
    private javax.swing.JTextField portal3txt;
    private javax.swing.JTextField portal4txt;
    private javax.swing.JTextArea rankingtxt;
    private javax.swing.JTextField tiempoEventotxt;
    // End of variables declaration//GEN-END:variables
}
